### ISSUE TITLE
M&C 2025 Full Paper

### ISSUE THREAD

**Issue by LukeSeifert** [arfc/msr-spatial-dep#4]
# Question or discussion topic.

The M&C 2025 full paper submission deadline is currently November 1st at midnight, and I am requesting a review of my submission.

## Provide details.

There is still some analysis I'm looking at doing, but the draft is mostly complete at this point (possibly investigating varying the niobium removal rate to approach the MSRE experimental results).

## External context or references.

The paper has been emailed to the other co-authors for review and is located [here](https://github.com/LukeSeifert/msr-spatial-dep/blob/powerhist/docs/ModelingMSRNuclides_MC2025.pdf).

# How can this issue be closed?

The paper is reviewed, and I make the suggested changes.

**Comment by katyhuff** [comment]
![2024-10-30-seifert-ModelingMSRNuclides_MC2025 - annotated.pdf](https://github.com/user-attachments/files/17581408/2024-10-30-seifert-ModelingMSRNuclides_MC2025.-.annotated.pdf)

**Comment by katyhuff** [comment]
![2024-10-30-seifert-ModelingMSRNuclides_MC2025.pdf](https://github.com/user-attachments/files/17581422/2024-10-30-seifert-ModelingMSRNuclides_MC2025.pdf)

**Comment by munkm** [comment]
Here's my comments.  


[ModelingMSRNuclides_MC2025-1.pdf](https://github.com/user-attachments/files/17604109/ModelingMSRNuclides_MC2025-1.pdf)

**Comment by LukeSeifert** [comment]
Thank you for the comments!
